story_6/urls.py
from django.contrib import admin
from django.urls import *
from .views import *

app_name='story_6'
urlpatterns = [
	path('admin/', admin.site.urls),
    path('', index, name='index'),
]

website_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_6.urls')),
]

story_6/models.py
from django.utils import timezone
from datetime import datetime, date, timedelta
from django.db import models

class Status(models.Model):

    status = models.CharField(max_length=300)
    waktu = models.DateTimeField(default=timezone.now()+timedelta(hours=7))

    def __str__(self):
        return self.status

story_6/forms.py
from django import forms

class Add_Status(forms.Form):

	attrs_status = {
        'id': 'status',
        'type': 'textarea',
        'class': 'form-control',
        'placeholder': 'Nama Pengisi - Status Anda',
    }

	status = forms.CharField(max_length=300, widget = forms.Textarea(attrs=attrs_status))

story_6/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from datetime import datetime, date
from .forms import *
from .models import *
from django.urls import reverse

# Create your views here.
def index(request):

	if request.method == 'POST':
		form = Add_Status(request.POST)
		if form.is_valid():
			status_person = form.cleaned_data["status"]
			stat = Status(status = status_person)
			stat.save()

	form = Add_Status()
	schd = Status.objects.all()
	return render(request, 'index.html', {'form' : form, 'table': schd})

story_6/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>insanulfahmi</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
<body>

	<div class="container text-center">
		<b class="judul text-center" >Halo, Apa Kabar?</b>
	</div>

	<div class="row">
		<div class="col-sm-6 mx-auto" style="margin-top: 10px;">
			<form action="{% url 'story_6:index' %}" method="POST">
	           	{% csrf_token %}
	                {{ form.as_p }}
	                <br>

	            <div class="pull-right" style="margin-top: -20px;">
	                <button id="button-form" type="submit" class="btn btn-secondary" href="{% url 'story_6:index' %}">
	                    Submit
	                </button>
	            </div>
	        </form>
	   	</div>
	</div>


	<div class="container montserrat_font" style="margin-top: 50px">
		<table id='myStatus' class="table table-striped table-dark">
			<thead>
            	<tr>
                	<th class="col-status" scope="col">Status</th>
                	<th class="col-waktu" scope="col">Waktu</th>
            	</tr>
          	</thead>

          	<tbody>
            	{% for status in table %}
            	<tr>
              		<th scope="row">{{ status.status }}</th>
              		<td>{{ status.waktu }}</td>
            	</tr>
            	
            	{% endfor %}
          </tbody>
		</table>
	</div>


</body>
</html>